#!/usr/bin/env bash
# common.sh — shared helpers for create-tests scripts.
# Sourced by every top-level script and by the lang-*.sh libs.
# Responsibilities: locate the skill dir, detect language from a path, and
# dispatch to the matched language lib. Logging goes to STDERR.

# --- Paths ------------------------------------------------------------------
_COMMON_SRC="${BASH_SOURCE[0]}"
LIB_DIR="$(cd "$(dirname "$_COMMON_SRC")" && pwd)"
SCRIPTS_DIR="$(cd "$LIB_DIR/.." && pwd)"
SKILL_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
export SKILL_DIR SCRIPTS_DIR LIB_DIR

# --- Logging ----------------------------------------------------------------
log()  { printf '%s\n' "$*" >&2; }
warn() { printf '⚠ %s\n' "$*" >&2; }
die()  { printf '✖ %s\n' "$*" >&2; exit 1; }

# --- Watermark (configurable attribution) -----------------------------------
# Header line prepended to generated specs (code-comment form). Configurable via
# <repo-root>/supensour-config.yaml (`watermark_template` or per-skill
# `skills.create-tests.watermark_template`). Placeholder {skillName} → "supensour:create-tests".
# The model fetches the resolved text via scripts/watermark.sh; WATERMARK_TEXT set at end of file.
SKILL_NAME="supensour:create-tests"
WATERMARK_DEFAULT="Generated by {skillName} · suprayan@supensour · github.com/supensour/supensour-agent"
AUTHOR_DEFAULT="suprayan-agent@supensour"
# watermark_banner — one-line console attribution to stderr (call once per run).
watermark_banner() { printf '🤖 %s\n' "$WATERMARK_TEXT" >&2; }

wm_cfg_file() {
  local f="$SKILL_DIR/../../supensour-config.yaml"
  [ -f "$f" ] && { printf '%s' "$f"; return 0; }
  return 1
}
_wm_top() {
  local f; f="$(wm_cfg_file)" || return 1
  awk '/^watermark_template:/{sub(/^watermark_template:/,""); print; exit}' "$f" | _clean_val
}
_wm_skill() {
  local f skill="$1"; f="$(wm_cfg_file)" || return 1
  awk -v s="$skill" '
    /^skills:[[:space:]]*$/        { ins=1; next }
    ins && /^[^[:space:]]/         { ins=0 }
    ins && $0 ~ "^  " s ":[[:space:]]*$" { inb=1; next }
    inb && /^  [^[:space:]]/       { inb=0 }
    inb && /^    watermark_template:/ { sub(/^    watermark_template:/,""); print; exit }
  ' "$f" | _clean_val
}
resolve_watermark() {
  local t; t="$(_wm_skill create-tests 2>/dev/null || true)"
  [ -z "$t" ] && t="$(_wm_top 2>/dev/null || true)"
  [ -z "$t" ] && t="$WATERMARK_DEFAULT"
  printf '%s' "${t//\{skillName\}/$SKILL_NAME}"
}
# author: skills.create-tests.author > top-level author > built-in default.
_author_top()   { local f; f="$(wm_cfg_file)" || return 1; awk '/^author:/{sub(/^author:/,""); print; exit}' "$f" | _clean_val; }
_author_skill() {
  local f; f="$(wm_cfg_file)" || return 1
  awk '
    /^skills:[[:space:]]*$/        { ins=1; next }
    ins && /^[^[:space:]]/         { ins=0 }
    ins && /^  create-tests:[[:space:]]*$/ { inb=1; next }
    inb && /^  [^[:space:]]/       { inb=0 }
    inb && /^    author:/          { sub(/^    author:/,""); print; exit }
  ' "$f" | _clean_val
}
resolve_author() {
  local a; a="$(_author_skill 2>/dev/null || true)"
  [ -z "$a" ] && a="$(_author_top 2>/dev/null || true)"
  [ -z "$a" ] && a="$AUTHOR_DEFAULT"
  printf '%s' "$a"
}

# --- Project config (hints to skip detection) -------------------------------
# <repo>/.supensour/config/config.yaml, nested git:/project: schema.
# create-tests reads project.language (default --lang) and git.base_branch (diff base).
proj_cfg_file() {
  local root; root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  [ -n "$root" ] && [ -f "$root/.supensour/config/config.yaml" ] && {
    printf '%s' "$root/.supensour/config/config.yaml"; return 0; }
  return 1
}
_clean_val() {
  sed -E 's/[[:space:]]+#.*$//; s/\r//g; s/^[[:space:]]+//; s/[[:space:]]+$//; s/^["'"'"']//; s/["'"'"']$//'
}
# proj_get <section> <field> — scalar from project config (section = git|project).
proj_get() {
  local f section="$1" field="$2"; f="$(proj_cfg_file)" || return 1
  awk -v section="$section" -v field="$field" '
    $0 ~ "^" section ":[[:space:]]*$" { inblk=1; next }
    inblk && /^[^[:space:]]/          { inblk=0 }
    inblk && $0 ~ "^  " field ":" {
      sub("^  " field ":", "")
      print; exit
    }
  ' "$f" | _clean_val
}

# ensure_project_config — create <repo>/.supensour/config/config.yaml if absent (commented hints).
ensure_project_config() {
  local root; root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  [ -z "$root" ] && return 0
  local f="$root/.supensour/config/config.yaml"
  [ -f "$f" ] && return 0
  mkdir -p "$(dirname "$f")"
  cat > "$f" <<'EOF'
# yaml-language-server: $schema=https://raw.githubusercontent.com/supensour/supensour-agent/master/schemas/project-config.schema.json
# Supensour per-repo hints (optional). Uncomment + set to skip detection.
git:
  # platform: gitlab-ce          # key into ~/.supensour/config/supensour.yaml platforms
  # token_env: GITLAB_TOKEN      # override the platform's token_env for this repo
  # base_branch: develop         # default diff base
project:
  # language: vue                # default --lang (review-code / create-tests)
  # test_type: unit              # default --type (create-tests)
EOF
  log "📝 Created $f — uncomment hints as needed."
}

# --- Language detection -----------------------------------------------------
# detect_lang <path> → vue | springboot | "" (unknown). Extension-based, mirrors
# the review-code rule-loading map.
detect_lang() {
  case "$1" in
    *.vue|*.ts|*.tsx|*.js|*.jsx|*.mjs|*.cjs) printf 'vue' ;;
    *.java|*.kt)                              printf 'springboot' ;;
    *) : ;;
  esac
}

# detect_lang_for_set <file...> → the dominant language across files (first match wins).
detect_lang_for_set() {
  local f l
  for f in "$@"; do l="$(detect_lang "$f")"; [ -n "$l" ] && { printf '%s' "$l"; return 0; }; done
  return 1
}

# --- Dispatch ---------------------------------------------------------------
# load_lang <lang> — source the matching lang-<lang>.sh.
load_lang() {
  local lang="$1" lib="$LIB_DIR/lang-${1}.sh"
  [ -n "$lang" ] || die "No language given/detected. Use --lang vue|springboot."
  [ -f "$lib" ] || die "No lang lib for '$lang' ($lib). Add it to extend support."
  # shellcheck disable=SC1090
  . "$lib"
  LANG_KEY="$lang"
}

# lang_dispatch <fn-suffix> [args...] → calls <lang>_<fn-suffix>.
# e.g. lang_dispatch run_tests <spec> <src> → vue_run_tests <spec> <src>
lang_dispatch() {
  local fn="${LANG_KEY}_$1"; shift
  if ! declare -F "$fn" >/dev/null; then
    die "Language '$LANG_KEY' does not implement '$fn'."
  fi
  "$fn" "$@"
}

# Resolve watermark + author now that _clean_val is defined.
WATERMARK_TEXT="$(resolve_watermark)"
AUTHOR_TEXT="$(resolve_author)"
export WATERMARK_TEXT AUTHOR_TEXT SKILL_NAME
